### ISSUE TITLE
(CloudWatchAttemptLogsProcessor): ineffective file reading byte-by-byte

### ISSUE THREAD

**Issue by bgklika** [aws-greengrass/aws-greengrass-log-manager#72]
**Describe the bug**
RandomAccessFile::readLine() actually read file byte-by-byte which is ugly wasteful.
See https://docs.oracle.com/javase/7/docs/api/java/io/RandomAccessFile.html#readLine()
I observe 100% load on 2 of 4 CPU cores.

**To Reproduce**
Just log 100 lines per second from your component or stop greengrass, create 10-20 big log files and start greengrass again. Using htop and strace -p PID  observe system calls.

**Expected behavior**
Usage of buffer at least 4k in size is expected.

**Actual behavior**
Nucleus thread eat to much CPU when read the log files.

**Environment**
 - Ubuntu 20.04
 - JDK version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
 - Nucleus version: 2.5.0
 - Log Manager version:   2.2.1

**Additional context**
Impact: system load

**Comment by MikeDombo** [comment]
Hello @bgklika,
Thank you for reporting this issue with the IO efficiency due to the usage of `RandomAccessFile`. I believe that I have resolved it in #73. Please feel free to use that branch to build your own copy of Log Manager, upload it to your Greengrass account and give it a try to see if it helps you.


Thank you again.
